--------------------------------------------------------
--  File created - Friday-August-11-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APARTMENTS
--------------------------------------------------------

  CREATE TABLE "AERO"."APARTMENTS" 
   (	"APARTMENT_ID" NUMBER(*,0), 
	"BOOKED_FROM" TIMESTAMP (6), 
	"BOOKED_TO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AERO.APARTMENTS
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index APARTMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AERO"."APARTMENTS_PK" ON "AERO"."APARTMENTS" ("APARTMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APARTMENTS
--------------------------------------------------------

  ALTER TABLE "AERO"."APARTMENTS" ADD CONSTRAINT "APARTMENTS_PK" PRIMARY KEY ("APARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AERO"."APARTMENTS" MODIFY ("APARTMENT_ID" NOT NULL ENABLE);
